{% set name = "scri" %}
{% set version = "2020.11.24.22.57.48" %}
{% set sha256 = "06b3f070a61907cb1c6315456bbf491f0a6c5ccad0e02358fb459c08ed637782" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: package_version={{ version }} {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy >=1.13
    - scipy
    - matplotlib-base
    - h5py
    - numba
    - quaternion >=2019.7.15.12.50.36
    - spherical_functions
    - spinsfast
    - sxs

test:
  imports:
    - scri

about:
  home: https://github.com/moble/scri
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python/numba code for manipulating time-dependent functions of spin-weighted spherical harmonics
  description: |
    This package collects a number of functions for constructing and manipulating gravitational
    waveforms, including rotating, determining the angular velocity, finding the co-precessing and
    co-rotating frames, and applying boosts, translations, and supertranslations.
  dev_url: https://github.com/moble/scri

extra:
  recipe-maintainers:
    - moble
