{% set name = "scri" %}
{% set version = "2019.6.5.13.20.47" %}
{% set sha256 = "0d5969392f78582d1013079df13f472c0a05465c8a82bf706ce3082d13217c5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: package_version={{ version }} {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13
    - scipy
    - numba
    - quaternion
    - spherical_functions
    - spinsfast
    - sxs

test:
  imports:
    - scri

about:
  home: http://github.com/moble/scri
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python/numba code for manipulating time-dependent functions of spin-weighted spherical harmonics'
  description: |
    This package collects a number of functions for constructing and manipulating gravitational
    waveforms, including rotating, determining the angular velocity, finding the co-precessing and
    co-rotating frames, and applying boosts, translations, and supertranslations.
  dev_url: https://github.com/moble/scri

extra:
  recipe-maintainers:
    - moble
