{% set name = "scri" %}
{% set version = "2022.8.4" %}
{% set sha256 = "27ac97eaa40dc4c892746b2e74cb78bf1cb14b51d14fc52341d624f9e41a0c04" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.8,<3.11
  run:
    - matplotlib-base
    - quaternion >=2022.4
    - python >=3.8,<3.11
    - spherical_functions >=2022.4
    - spinsfast >=2022.4
    - sxs >=2022.3.4

test:
  requires:
    - pip
  imports:
    - scri
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show scri

about:
  home: https://github.com/moble/scri
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python/numba code for manipulating time-dependent functions of spin-weighted spherical harmonics
  description: |
    This package collects a number of functions for constructing and manipulating gravitational
    waveforms, including rotating, determining the angular velocity, finding the co-precessing and
    co-rotating frames, and applying boosts, translations, and supertranslations.
  dev_url: https://github.com/moble/scri

extra:
  recipe-maintainers:
    - moble
