{% set name = "scri" %}
{% set version = "2022.7.1" %}
{% set sha256 = "ca9de5b27eab63fe8e29ad509756b83c5def5b2eb5e18b590894c4e2b5c812b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win or py<38]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python {{ python }}
    - poetry-core
    - pip
  run:
    - python {{ python }}
    - matplotlib-base
    - quaternion >=2022.4
    - spherical_functions >=2022.4
    - spinsfast >=2022.4
    - sxs >=2022.3.4

test:
  imports:
    - scri

about:
  home: https://github.com/moble/scri
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python/numba code for manipulating time-dependent functions of spin-weighted spherical harmonics
  description: |
    This package collects a number of functions for constructing and manipulating gravitational
    waveforms, including rotating, determining the angular velocity, finding the co-precessing and
    co-rotating frames, and applying boosts, translations, and supertranslations.
  dev_url: https://github.com/moble/scri

extra:
  recipe-maintainers:
    - moble
